Repository ssafy-zippt-team/zippt-backend-project, pull requests merged in 2025-05, with the labels that each got.

#6 fix5 에러 수정 완료
  src/main/resources/mappers/review.xml
Labels: bug

#9 ✨: FEAURE : Add Spring Security
  pom.xml
  src/main/java/com/ssafy/home/Heo/commercial/controller/CommercialController.java
  src/main/java/com/ssafy/home/Heo/common/base/BaseResponse.java
  src/main/java/com/ssafy/home/Heo/config/CorsMvcConfig.java
  src/main/java/com/ssafy/home/Heo/config/SecurityConfig.java
  src/main/java/com/ssafy/home/Heo/security/controller/JWTController.java
  src/main/java/com/ssafy/home/Heo/security/controller/RefreshController.java
  src/main/java/com/ssafy/home/Heo/security/dto/in/IssueRefreshTokenDto.java
  src/main/java/com/ssafy/home/Heo/security/dto/in/RegistRequestDto.java
  src/main/java/com/ssafy/home/Heo/security/dto/in/UserDetailRequestDto.java
  src/main/java/com/ssafy/home/Heo/security/dto/out/CustomUserDetails.java
  src/main/java/com/ssafy/home/Heo/security/dto/out/RefreshTokenResponseDto.java
  src/main/java/com/ssafy/home/Heo/security/dto/out/RegistResponseDto.java
  src/main/java/com/ssafy/home/Heo/security/dto/out/UserDetailResponseDto.java
  src/main/java/com/ssafy/home/Heo/security/entity/RefreshTokenEntity.java
  src/main/java/com/ssafy/home/Heo/security/entity/UserEntity.java
  src/main/java/com/ssafy/home/Heo/security/exception/JwtExceptionHandler.java
  src/main/java/com/ssafy/home/Heo/security/jwt/JWTFilter.java
  src/main/java/com/ssafy/home/Heo/security/jwt/JWTUtil.java
  src/main/java/com/ssafy/home/Heo/security/jwt/LoginFilter.java
  src/main/java/com/ssafy/home/Heo/security/repository/RefreshTokenDao.java
  src/main/java/com/ssafy/home/Heo/security/repository/UserDao.java
  src/main/java/com/ssafy/home/Heo/security/service/CustomUserDetailsService.java
  src/main/java/com/ssafy/home/Heo/security/service/JoinService.java
  src/main/java/com/ssafy/home/Heo/security/service/RefreshTokenService.java
  src/main/java/com/ssafy/home/Heo/security/vo/in/IssueRefreshTokenVo.java
  src/main/java/com/ssafy/home/Heo/security/vo/in/RegistRequestVo.java
  src/main/java/com/ssafy/home/Heo/security/vo/out/RefreshTokenCheckVo.java
  src/main/java/com/ssafy/home/Heo/security/vo/out/UserDetailResponseVo.java
  src/main/resources/mappers/RefreshToken.xml
  src/main/resources/mappers/User.xml
Labels: enhancement

#11 핵심기능 AI 평가 및 요약 프롬프트 개선
  src/main/java/com/ssafy/home/Heo/ai/dto/in/HouseInfoRequestDto.java
  src/main/java/com/ssafy/home/Heo/ai/service/HouseSummaryServiceImpl.java
  src/main/java/com/ssafy/home/Heo/security/jwt/JWTUtil.java
Labels: documentation

#13 최근검색어 캐싱 완료 및 아파트상세 조회 dto vo 스펙 변경
  src/main/java/com/ssafy/home/Heo/cache/controller/CacheController.java
  src/main/java/com/ssafy/home/Heo/cache/dto/out/RecentSearchResponseDto.java
  src/main/java/com/ssafy/home/Heo/cache/dto/out/SearchWordDetailResponseDto.java
  src/main/java/com/ssafy/home/Heo/cache/service/RedisService.java
  src/main/java/com/ssafy/home/Heo/cache/service/RedisServiceImpl.java
  src/main/java/com/ssafy/home/Heo/cache/vo/out/RecentSearchResponseVo.java
  src/main/java/com/ssafy/home/Heo/cache/vo/out/SearchWordDetailResponseVo.java
  src/main/java/com/ssafy/home/Heo/house/controller/HouseController.java
  src/main/java/com/ssafy/home/Heo/house/dto/out/HouseAmountResponseDto.java
  src/main/java/com/ssafy/home/Heo/house/dto/out/HouseDetailResponseDto.java
  src/main/java/com/ssafy/home/Heo/house/repository/HouseDao.java
  src/main/java/com/ssafy/home/Heo/house/service/HouseServiceImpl.java
  src/main/java/com/ssafy/home/Heo/house/vo/out/HouseDetailResponseVo.java
  src/main/resources/mappers/house.xml
Labels: enhancement

#24 feat23 : 즐겨찾기기기능 추가
  src/main/java/com/ssafy/home/Heo/bookmark/controller/BookMarkController.java
  src/main/java/com/ssafy/home/Heo/bookmark/repository/BookmarkDao.java
  src/main/java/com/ssafy/home/Heo/bookmark/service/BookmarkService.java
  src/main/java/com/ssafy/home/Heo/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/ssafy/home/Heo/house/dto/out/HouseDetailResponseDto.java
  src/main/java/com/ssafy/home/Heo/house/vo/out/HouseDetailResponseVo.java
  src/main/java/com/ssafy/home/Heo/member/controller/MemberController.java
  src/main/resources/mappers/bookmark.xml
Labels: enhancement
